exports.getPairAndFormat = {
  format: ['1', '2', '3'],
  pair: [
    'BTCUSDT',
    'ETHUSDT',
    'XRPUSDT',
    'DOGEUSDT',
    'BNBUSDT',
    'ADAUSDT',
    'SOLUSDT',
    'MATICUSDT',
    'DOTUSDT',
    'AVAXUSDT',
    'ATOMUSDT',
    'LTCUSDT',
    'LINKUSDT',
    'ETCUSDT',
    'NEARUSDT',
    'ALGOUSDT',
    'QNTUSDT',
    'APEUSDT',
    'CHRUSDT',
    'CHRUSDT',
    'SANDUSDT',
    'MANAUSDT',
    'THETAUSDT',
    'APTUSDT',
    'AXSUSDT',
    'KLAYUSDT',
    'XECUSDT',
    'FTMUSDT',
    'PAXGUSDT',
    'MINAUSDT',
    'WAVESUSDT',
    'HOTUSDT',
  ],
}
